JOB_STATUS_QUEUED = "queued"
JOB_STATUS_RUNNING = "running"
JOB_STATUS_SUCCEEDED = "succeeded"
JOB_STATUS_FAILED = "failed"
JOB_STATUS_CANCELLED = "cancelled"
JOB_STATUS_SKIPPED = "skipped"

JOB_STATUSES = {
    JOB_STATUS_QUEUED,
    JOB_STATUS_RUNNING,
    JOB_STATUS_SUCCEEDED,
    JOB_STATUS_FAILED,
    JOB_STATUS_CANCELLED,
    JOB_STATUS_SKIPPED,
}

ACTIVE_JOB_STATUSES = {JOB_STATUS_QUEUED, JOB_STATUS_RUNNING}
TERMINAL_JOB_STATUSES = {
    JOB_STATUS_SUCCEEDED,
    JOB_STATUS_FAILED,
    JOB_STATUS_CANCELLED,
    JOB_STATUS_SKIPPED,
}

JOB_KIND_BASIC_FILE_PROCESSING = "basic_file_processing"
JOB_KIND_DOCUMENT_PARSE = "document_parse"
JOB_KIND_DOCUMENT_TRANSLATE = "document_translate"
JOB_KIND_DOCUMENT_EMBEDDING = "document_embedding"
JOB_KIND_DOCUMENT_SUMMARY = "document_summary"
JOB_KIND_DOCUMENT_KG_EXTRACT = "document_kg_extract"
JOB_KIND_DOCUMENT_OCR_RETRY = "document_ocr_retry"
JOB_KIND_BATCH_IMPORT = "batch_import"

JOB_KINDS = {
    JOB_KIND_BASIC_FILE_PROCESSING,
    JOB_KIND_DOCUMENT_PARSE,
    JOB_KIND_DOCUMENT_TRANSLATE,
    JOB_KIND_DOCUMENT_EMBEDDING,
    JOB_KIND_DOCUMENT_SUMMARY,
    JOB_KIND_DOCUMENT_KG_EXTRACT,
    JOB_KIND_DOCUMENT_OCR_RETRY,
    JOB_KIND_BATCH_IMPORT,
}

SUBJECT_TYPE_DOCUMENT = "document"
SUBJECT_TYPE_FILE = "file"
SUBJECT_TYPE_BATCH = "batch"
